server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    # No cachear el index.html para evitar JS viejo
    location = /index.html {
        add_header Cache-Control "no-store, no-cache, must-revalidate";
    }

    location / {
        try_files $uri $uri/ /index.html;
    }

    # Assets con hash en el nombre -> cachear agresivamente
    location /assets/ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }

    location /api/ {
        proxy_pass http://api-gateway:3000/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Proxy para archivos de evidencia de entrega
    location /uploads/ {
        proxy_pass http://api-gateway:3000/uploads/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
