# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fx_service.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x66x_service.proto\x12\x02\x66x\"A\n\x13\x45xchangeRateRequest\x12\x15\n\rfrom_currency\x18\x01 \x01(\t\x12\x13\n\x0bto_currency\x18\x02 \x01(\t\"\x8c\x01\n\x14\x45xchangeRateResponse\x12\x15\n\rfrom_currency\x18\x01 \x01(\t\x12\x13\n\x0bto_currency\x18\x02 \x01(\t\x12\x0c\n\x04rate\x18\x03 \x01(\x01\x12\x11\n\ttimestamp\x18\x04 \x01(\x03\x12\x12\n\nfrom_cache\x18\x05 \x01(\x08\x12\x13\n\x0bis_fallback\x18\x06 \x01(\x08\"H\n\x14MultipleRatesRequest\x12\x15\n\rbase_currency\x18\x01 \x01(\t\x12\x19\n\x11target_currencies\x18\x02 \x03(\t\"\xb8\x01\n\x15MultipleRatesResponse\x12\x15\n\rbase_currency\x18\x01 \x01(\t\x12\x33\n\x05rates\x18\x02 \x03(\x0b\x32$.fx.MultipleRatesResponse.RatesEntry\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\x12\x12\n\nfrom_cache\x18\x04 \x01(\x08\x1a,\n\nRatesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x01:\x02\x38\x01\x32\x9a\x01\n\tFXService\x12\x44\n\x0fGetExchangeRate\x12\x17.fx.ExchangeRateRequest\x1a\x18.fx.ExchangeRateResponse\x12G\n\x10GetMultipleRates\x12\x18.fx.MultipleRatesRequest\x1a\x19.fx.MultipleRatesResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fx_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_MULTIPLERATESRESPONSE_RATESENTRY']._options = None
  _globals['_MULTIPLERATESRESPONSE_RATESENTRY']._serialized_options = b'8\001'
  _globals['_EXCHANGERATEREQUEST']._serialized_start=24
  _globals['_EXCHANGERATEREQUEST']._serialized_end=89
  _globals['_EXCHANGERATERESPONSE']._serialized_start=92
  _globals['_EXCHANGERATERESPONSE']._serialized_end=232
  _globals['_MULTIPLERATESREQUEST']._serialized_start=234
  _globals['_MULTIPLERATESREQUEST']._serialized_end=306
  _globals['_MULTIPLERATESRESPONSE']._serialized_start=309
  _globals['_MULTIPLERATESRESPONSE']._serialized_end=493
  _globals['_MULTIPLERATESRESPONSE_RATESENTRY']._serialized_start=449
  _globals['_MULTIPLERATESRESPONSE_RATESENTRY']._serialized_end=493
  _globals['_FXSERVICE']._serialized_start=496
  _globals['_FXSERVICE']._serialized_end=650
# @@protoc_insertion_point(module_scope)
