apiVersion: v1
kind: ConfigMap
metadata:
  name: delivereats-config
  namespace: delivereats
  labels:
    app: delivereats
data:
  # Auth Service
  AUTH_SERVICE_HOST: "auth-service:50051"
  # Restaurant Catalog Service
  RESTAURANT_SERVICE_HOST: "restaurant-catalog-service:50052"
  # Order Service
  ORDER_SERVICE_HOST: "order-service:50053"
  # Delivery Service
  DELIVERY_SERVICE_HOST: "delivery-service:50054"
  # Notification Service
  NOTIFICATION_SERVICE_HOST: "notification-service:50055"
  # FX Service
  FX_SERVICE_HOST: "fx-service:50056"
  # Payment Service
  PAYMENT_SERVICE_HOST: "payment-service:50057"
  # Redis
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  # RabbitMQ
  RABBITMQ_URL: "amqp://delivereats:delivereats2026@rabbitmq:5672"
  # Database common config
  DB_PORT: "5432"
  DB_USER: "postgres"
  DB_HOST: "localhost"
  # Flask / FX
  FLASK_PORT: "5000"
  GRPC_PORT: "50056"
  EXCHANGE_API_KEY: ""
  # SMTP
  SMTP_HOST: "smtp.gmail.com"
  SMTP_PORT: "587"
