apiVersion: v1
kind: Secret
metadata:
  name: delivereats-secrets
  namespace: delivereats
  labels:
    app: delivereats
type: Opaque
stringData:
  JWT_SECRET: "delivereats_secret_key_sa_2026"
  DB_PASSWORD: "postgres"
  SMTP_USER: "jalbertochigua@gmail.com"
  SMTP_PASS: "xyjd snzf dgsh ptls"
  RABBITMQ_DEFAULT_USER: "delivereats"
  RABBITMQ_DEFAULT_PASS: "delivereats2026"
